// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TribeWallet.Data;

#nullable disable

namespace TribeWallet.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909223259_AdicionarTimestampsESoftDelete")]
    partial class AdicionarTimestampsESoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TribeWallet.Domain.Entities.CompromissoFinanceiro", b =>
                {
                    b.Property<Guid>("CompromissoFinanceiroId")
                        .HasColumnType("uuid")
                        .HasColumnName("compromisso_financeiro_id");

                    b.Property<string>("Categoria")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Imagem")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("imagem");

                    b.Property<int>("TipoDivisao")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_divisao");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("CompromissoFinanceiroId")
                        .HasName("pk_compromissos_financeiros");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_compromissos_financeiros_data");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_compromissos_financeiros_deleted_at");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_compromissos_financeiros_grupo_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_compromissos_financeiros_token");

                    b.ToTable("compromissos_financeiros", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Grupo", b =>
                {
                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nome");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("GrupoId")
                        .HasName("pk_grupos");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_grupos_deleted_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_grupos_token");

                    b.ToTable("grupos", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.HistoricoAlteracao", b =>
                {
                    b.Property<Guid>("HistoricoAlteracaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("historico_alteracao_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DadosAntes")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_antes");

                    b.Property<string>("DadosDepois")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados_depois");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entidade");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("HistoricoAlteracaoId")
                        .HasName("pk_historico_alteracoes");

                    b.HasIndex("DataHora")
                        .HasDatabaseName("ix_historico_alteracoes_data_hora");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_historico_alteracoes_deleted_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_historico_alteracoes_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_historico_alteracoes_usuario_id");

                    b.HasIndex("Entidade", "EntidadeId")
                        .HasDatabaseName("ix_historico_alteracoes_entidade_entidade_id");

                    b.ToTable("historico_alteracoes", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Integrante", b =>
                {
                    b.Property<Guid>("IntegranteId")
                        .HasColumnType("uuid")
                        .HasColumnName("integrante_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("IntegranteId")
                        .HasName("pk_integrantes");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_integrantes_deleted_at");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_integrantes_grupo_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_integrantes_token");

                    b.HasIndex("UsuarioId", "GrupoId")
                        .IsUnique()
                        .HasDatabaseName("ix_integrantes_usuario_id_grupo_id");

                    b.ToTable("integrantes", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.IntegranteCompromisso", b =>
                {
                    b.Property<Guid>("IntegranteCompromissoId")
                        .HasColumnType("uuid")
                        .HasColumnName("integrante_compromisso_id");

                    b.Property<Guid>("CompromissoId")
                        .HasColumnType("uuid")
                        .HasColumnName("compromisso_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IntegranteId")
                        .HasColumnType("uuid")
                        .HasColumnName("integrante_id");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("ValorDevedor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor_devedor");

                    b.Property<decimal>("ValorPago")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("valor_pago");

                    b.HasKey("IntegranteCompromissoId")
                        .HasName("pk_integrantes_compromissos");

                    b.HasIndex("CompromissoId")
                        .HasDatabaseName("ix_integrantes_compromissos_compromisso_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_integrantes_compromissos_deleted_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_integrantes_compromissos_token");

                    b.HasIndex("IntegranteId", "CompromissoId")
                        .IsUnique()
                        .HasDatabaseName("ix_integrantes_compromissos_integrante_id_compromisso_id");

                    b.ToTable("integrantes_compromissos", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Notificacao", b =>
                {
                    b.Property<Guid>("NotificacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("notificacao_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_envio");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("entidade");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uuid")
                        .HasColumnName("entidade_id");

                    b.Property<bool>("Lida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("lida");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensagem");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UsuarioDestinoId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_destino_id");

                    b.Property<Guid?>("UsuarioOrigemId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_origem_id");

                    b.HasKey("NotificacaoId")
                        .HasName("pk_notificacoes");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_notificacoes_deleted_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_notificacoes_token");

                    b.HasIndex("UsuarioOrigemId")
                        .HasDatabaseName("ix_notificacoes_usuario_origem_id");

                    b.HasIndex("Entidade", "EntidadeId")
                        .HasDatabaseName("ix_notificacoes_entidade_entidade_id");

                    b.HasIndex("UsuarioDestinoId", "Lida")
                        .HasDatabaseName("ix_notificacoes_usuario_destino_id_lida");

                    b.ToTable("notificacoes", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Pagamento", b =>
                {
                    b.Property<Guid>("PagamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pagamento_id");

                    b.Property<string>("ComprovanteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("comprovante_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("IntegranteCompromissoId")
                        .HasColumnType("uuid")
                        .HasColumnName("integrante_compromisso_id");

                    b.Property<int>("Metodo")
                        .HasColumnType("integer")
                        .HasColumnName("metodo");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal>("Valor")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)")
                        .HasColumnName("valor");

                    b.HasKey("PagamentoId")
                        .HasName("pk_pagamentos");

                    b.HasIndex("Data")
                        .HasDatabaseName("ix_pagamentos_data");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_pagamentos_deleted_at");

                    b.HasIndex("IntegranteCompromissoId")
                        .HasDatabaseName("ix_pagamentos_integrante_compromisso_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_pagamentos_token");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Relatorio", b =>
                {
                    b.Property<Guid>("RelatorioId")
                        .HasColumnType("uuid")
                        .HasColumnName("relatorio_id");

                    b.Property<Guid>("CompromissoId")
                        .HasColumnType("uuid")
                        .HasColumnName("compromisso_id");

                    b.Property<string>("ConteudoUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("conteudo_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_hora");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("RelatorioId")
                        .HasName("pk_relatorios");

                    b.HasIndex("CompromissoId")
                        .HasDatabaseName("ix_relatorios_compromisso_id");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_relatorios_deleted_at");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_relatorios_token");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_relatorios_usuario_id");

                    b.ToTable("relatorios", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("HashSenha")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hash_senha");

                    b.Property<string>("Imagem")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("imagem");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sobrenome");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("character(64)")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UsuarioId")
                        .HasName("pk_usuarios");

                    b.HasIndex("DeletedAt")
                        .HasDatabaseName("ix_usuarios_deleted_at");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_email");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_token");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_usuarios_username");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.CompromissoFinanceiro", b =>
                {
                    b.HasOne("TribeWallet.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Compromissos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_compromissos_financeiros_grupos_grupo_id");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.HistoricoAlteracao", b =>
                {
                    b.HasOne("TribeWallet.Domain.Entities.Usuario", "Usuario")
                        .WithMany("HistoricoAlteracoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_historico_alteracoes_usuarios_usuario_id");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Integrante", b =>
                {
                    b.HasOne("TribeWallet.Domain.Entities.Grupo", "Grupo")
                        .WithMany("Integrantes")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integrantes_grupos_grupo_id");

                    b.HasOne("TribeWallet.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Integrantes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integrantes_usuarios_usuario_id");

                    b.Navigation("Grupo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.IntegranteCompromisso", b =>
                {
                    b.HasOne("TribeWallet.Domain.Entities.CompromissoFinanceiro", "Compromisso")
                        .WithMany("Participacoes")
                        .HasForeignKey("CompromissoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integrantes_compromissos_compromissos_financeiros_compromis");

                    b.HasOne("TribeWallet.Domain.Entities.Integrante", "Integrante")
                        .WithMany("Compromissos")
                        .HasForeignKey("IntegranteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_integrantes_compromissos_integrantes_integrante_id");

                    b.Navigation("Compromisso");

                    b.Navigation("Integrante");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Notificacao", b =>
                {
                    b.HasOne("TribeWallet.Domain.Entities.Usuario", "UsuarioDestino")
                        .WithMany("NotificacoesRecebidas")
                        .HasForeignKey("UsuarioDestinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notificacoes_usuarios_usuario_destino_id");

                    b.HasOne("TribeWallet.Domain.Entities.Usuario", "UsuarioOrigem")
                        .WithMany("NotificacoesEnviadas")
                        .HasForeignKey("UsuarioOrigemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notificacoes_usuarios_usuario_origem_id");

                    b.Navigation("UsuarioDestino");

                    b.Navigation("UsuarioOrigem");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Pagamento", b =>
                {
                    b.HasOne("TribeWallet.Domain.Entities.IntegranteCompromisso", "IntegranteCompromisso")
                        .WithMany("Pagamentos")
                        .HasForeignKey("IntegranteCompromissoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pagamentos_integrantes_compromissos_integrante_compromisso_");

                    b.Navigation("IntegranteCompromisso");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Relatorio", b =>
                {
                    b.HasOne("TribeWallet.Domain.Entities.CompromissoFinanceiro", "Compromisso")
                        .WithMany("Relatorios")
                        .HasForeignKey("CompromissoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relatorios_compromissos_financeiros_compromisso_id");

                    b.HasOne("TribeWallet.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Relatorios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relatorios_usuarios_usuario_id");

                    b.Navigation("Compromisso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.CompromissoFinanceiro", b =>
                {
                    b.Navigation("Participacoes");

                    b.Navigation("Relatorios");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("Compromissos");

                    b.Navigation("Integrantes");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Integrante", b =>
                {
                    b.Navigation("Compromissos");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.IntegranteCompromisso", b =>
                {
                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("TribeWallet.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("HistoricoAlteracoes");

                    b.Navigation("Integrantes");

                    b.Navigation("NotificacoesEnviadas");

                    b.Navigation("NotificacoesRecebidas");

                    b.Navigation("Relatorios");
                });
#pragma warning restore 612, 618
        }
    }
}
